config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: "General::User", controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  namespace :admin do
    post "upload", to: "attachments#upload"
    get "users/images_approbation", to: "users#images_approbation"
    get "analytics", to: "analytics#index"
    get "search", to: "search#search"
    
    resources :profiles do
      get :users_list, on: :member
    end

    resources :users

    resources :helpcenter_questions do
      get :subcategories, on: :collection
    end
    resources :helpcenter_categories do
      get :assistants, on: :member
    end
    resources :helpcenter_tickets do
      get :subcategories, on: :collection
      put :take_ticket, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      resources :helpcenter_messages, on: :member, only: [:create]
      get :tickets_list, on: :member
    end
    resources :expense_report_requests do
      put :take_request, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      get :requests_list, on: :member
      get :download_request_pdf, on: :member

    end
    resources :expense_report_categories 
    resource :chat_messages
    resource :chat_rooms

    root to: "helpcenter_tickets#index"
  end

  namespace :api, :defaults => { :format => "json" } do
    namespace :v1, :defaults => { :format => "json" } do
      resources :users, only: [:show] do
        post :sign_in, on: :collection
        delete :sign_out, on: :collection
        get :current_user_vue, on: :collection
      end

      post 'users', to: 'users#create_update'
      delete 'users', to: 'users#destroy'
      get 'search/users', to: 'users#search'

      get 'societies', to: 'societies#societies'
      get 'categories', to: 'expense_report_categories#categories' 
      
      resources :hc_questions, only: [:show] do
        get :importants, on: :collection
        get :search, on: :collection
      end
      post 'expense_report_requests/review_request', to: 'expense_report_requests#review_request' 
      get 'expense_report_requests/response_request', to: 'expense_report_requests#response_request' 
      get 'expense_report_requests/divisas', to: 'expense_report_requests#divisas'
      get 'expense_report_requests/countries', to: 'expense_report_requests#countries'
      get 'expense_report_requests/accounts', to: 'expense_report_requests#accounts'
      get 'expense_report_requests/payment_method', to: 'expense_report_requests#payment_method'
      post 'expense_report_requests/save_draft_request', to: 'expense_report_requests#save_draft_request'
      get 'expense_report_requests/request_draft', to: 'expense_report_requests#request_draft'
      get 'expense_report_requests/request_user', to: 'expense_report_requests#request_user'
      get 'expense_report_requests/pending_requests', to: 'expense_report_requests#pending_requests'
      resources :expense_report_requests do
        delete :destroy_file, on: :collection
        delete :destroy_invoice, on: :collection
      end
      resources :chat_messages, param: :slug, only: [:create]
      
      resources :hc_categories, param: :slug, only: [:index, :show]
      resources :hc_subcategories, param: :slug, only: [:show]
      
      resources :hc_tickets do
        get :divisas, on: :collection
        get :ofertas, on: :collection
        resources :hc_messages, on: :member, only: [:create]
        resources :hc_satisfaction_answers, on: :member, only: [:create]
        post :create_postulacion, on: :member
        get :index_job_applications, on: :collection
        patch :update_postulacion_status, on: :member
        put :assign_assistant, on: :member
      end
    end
    
    root to: "application#index"
  end

  root to: "application#index"
end

app/models/general/profile.rb
# frozen_string_literal: true

class General::Profile < ApplicationRecord
  class Classes
    ALL = %w[
      benefit_group
      office_city
      is_boss
      cost_center
      management
      company
      position_classification
      employee_classification
      office_region
      gender
      office_country
      has_children
      country
    ].freeze
  end

  has_many :user_profiles, class_name: 'General::UserProfile', foreign_key: :profile_id, inverse_of: :profile, dependent: :destroy
  has_many :profile_attributes, class_name: 'General::ProfileAttribute', foreign_key: :profile_id, inverse_of: :profile
  has_many :users, through: :user_profiles
  has_many :categories, class_name: 'Helpcenter::Category', foreign_key: :profile_id

  def set_users
    query = '1'
    class_name = nil
    users_ids = General::User.all.pluck(:id)
    Classes::ALL.each do |class_name|
      if profile_attributes.where(class_name: class_name).present?
        values = profile_attributes.where(class_name: class_name).pluck(:value)
        users_ids = General::UserAttribute.where(user_id: users_ids).where(attribute_name: class_name, value: values).pluck(:user_id).uniq
      end
    end

    query_profile_users = General::User.where(id: users_ids)
    if query_profile_users.present?
      new_users = query_profile_users - users
      remove_users = users - query_profile_users
    end

    if new_users.present?
      new_users.each do |user|
        users << user
      end
    end

    if remove_users.present?
      remove_users.each do |user|
        General::UserProfile.where(user_id: user.id, profile_id: id).destroy_all
      end
    end
  end

  def set_users_by_excel(ruts)
    users = []
    ruts.each do |rut|
      ln = rut.class ==  String ? rut : rut.to_i.to_s
      
      user = General::User.where(legal_number: ln[0...-1], legal_number_verification: ln[-1]).last  
      users << user if user.present?
    end

    new_users = users - self.users
    remove_users = self.users - users

    if new_users.present?
      new_users.each do |user|
        self.users << user
      end
    end

    if remove_users.present?
      remove_users.each do |user|
        General::UserProfile.where(user_id: user.id, profile_id: id).destroy_all
      end
    end
  end

  def set_query(class_name, query)
    profile_attributes_where = profile_attributes.where(class_name: class_name).map { |v| "'#{v.value}'" }.join(',')
    if profile_attributes_where.present?
      query + " AND (attribute_name = '#{class_name}' AND value IN (#{profile_attributes_where}))"
    end
  end

  def self.get_manager_profiles(current_user)
    profiles = []
    manager_companies = current_user.manager_companies.pluck(:company_id)
    
    all.each do |profile|
      # profile_companies = profile.users.pluck(:company_id).uniq
      profile_companies = profile.profile_attributes.where(class_name: "company").pluck(:value).map(&:to_i)
      
      if profile_companies.present? && profile_companies.count <= manager_companies.count
        profiles << profile if (profile_companies - manager_companies).count.zero?    
      end
    end

    profiles
  end

  def self.get_profiles(current_user)
    if current_user.is_admin?
      profiles = all.pluck(:name, :id).sort
    else
      profiles = get_manager_profiles(current_user).pluck(:name, :id).sort
    end
  end

  # "1 AND (attribute_name = 'gender' AND value IN ('Masculino, femenino')) AND (attribute_name = 'company' AND value IN ('2'))"
end

app/controllers/admin/profiles_controller.rb
# frozen_string_literal: true

module Admin
  class ProfilesController < AdminController
    before_action :set_profile, only: %i[show edit update destroy]

    def index
      @profiles = General::Profile.order(created_at: :desc)
    end

    def show
      country_ids = General::ProfileAttribute.where(profile: @profile, class_name: 'country').pluck(:value)
      @office_countries = Location::Country.find(country_ids)
    end

    def users_list
      @profile = General::Profile.includes(user_profiles: :user).find(params[:id])
      render xlsx: 'users_list.xlsx.axlsx', filename: "listado de usuarios #{@profile.name + ' ' + l(Date.today, format: '%A %d %B %Y')}.xlsx"
    end

    def new
      @profile = General::Profile.new
      get_data
    end

    def edit
      get_data
      get_selected
    end

    def create
      @profile = General::Profile.new(profile_params)
      @profile.attached = (params[:profile][:file].present? ? true : false)

      respond_to do |format|
        if @profile.save
          assign_users
          format.html { redirect_to admin_profile_path(@profile), notice: 'Profile fue creada con éxito.' }
          format.json { render :show, status: :created, location: @profile }
          format.js
        else
          format.html { render :new }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end

    def update
      respond_to do |format|
        @profile.attached = params[:creation_option] != 'manual'
        if @profile.update(profile_params)
          assign_users
          format.html { redirect_to admin_profile_path(@profile), notice: 'Profile fue actualizada con éxito.' }
          format.json { render :show, status: :ok, location: @profile }
        else
          format.html { render :edit }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @profile.destroy
      respond_to do |format|
        format.html { redirect_to admin_profiles_path, notice: 'Profile fue eliminada con éxito.' }
        format.json { head :no_content }
      end
    end

    private

    def assign_users
      ruts = read_xlsx
      if ruts.present?
        @profile.set_users_by_excel ruts
      elsif !@profile.attached
        set_profile_attributes
        @profile.set_users
      end
    end

    def read_xlsx
      data = nil
      file = params[:profile][:file]
      if file.present?
        xlsx = Roo::Spreadsheet.open(file.path)
        data = xlsx.sheet(0).column(1)
      end
      data
    end

    def set_profile_attributes
      # Para agregar un nuevo filtro, hay que también agregarlo en el array "ALL" dentro del modelo profile.
      set_class_name_value(params[:regions], 'region')
      set_class_name_value(params[:benefit_groups], 'benefit_group')
      set_class_name_value(params[:companies], 'company')
      set_class_name_value(params[:countries], 'country')
      set_class_name_value(params[:managements], 'management')
      set_class_name_value(params[:genders], 'gender')
      set_class_name_value(params[:is_boss], 'is_boss')
      set_class_name_value(params[:employee_classifications], 'employee_classification')
      set_class_name_value(params[:cost_centers], 'cost_center')
      set_class_name_value(params[:position_classifications], 'position_classification')
      set_class_name_value(params[:syndicate_members], 'syndicate_member')
      set_class_name_value(params[:contract_types], 'contract_type')
      set_class_name_value(params[:roles], 'rol')
      set_class_name_value(params[:schedules], 'schedule')
      set_class_name_value(params[:has_children], 'has_children')
      set_class_name_value(params[:office_countries], 'office_country')
      set_class_name_value(params[:office_cities], 'office_city')
      set_class_name_value(params[:office_regions], 'office_region')
      # set_class_name_value(params[:has_childrens], "has_children")
    end

    def get_data
      users = General::User.all
      @genders = %w[Masculino Femenino]
      @is_boss = { "Si": 1, "No": 0 }
      @employee_classifications = users.pluck(:employee_classification).uniq.reject(&:blank?).sort
      @regions = Location::Region.order(:name).pluck(:id, :name).uniq.reject(&:blank?)
      @companies = Company::Company.where.not(name: '').order(:name).pluck(:id, :name)
      @countries = Location::Country.where.not(name: '').order(:name).pluck(:id, :name)
      @managements = Company::Management.where.not(name: '').order(:name).pluck(:id, :name)
      @cost_centers = Company::CostCenter.where.not(name: '').order(:name).pluck(:id, :name)
      @position_classifications = users.pluck(:position_classification).uniq.reject(&:blank?).sort
      @syndicate_members = users.pluck(:syndicate_member).uniq.reject(&:blank?).sort
      @contract_types = users.pluck(:contract_type).uniq.reject(&:blank?).sort
      @roles = users.pluck(:rol).uniq.reject(&:blank?).sort
      @schedules = users.pluck(:schedule).uniq.reject(&:blank?).sort
      @has_children = { "Si": 1, "No": 0 }
      @office_countries = Location::Country.where.not(name: '').order(:name).map { |country| [country.name, country.id] }
      @office_cities = Location::City.where.not(name: '').order(:name).map { |city| [city.name, city.id] }
      @office_regions = Location::Region.where.not(name: '').order(:name).map { |region| [region.name, region.id] }
    end

    def get_selected
      @selected_countries = @profile.profile_attributes.where(class_name: 'country').pluck(:value)
      @selected_genders = @profile.profile_attributes.where(class_name: 'gender').pluck(:value)
      @selected_boss = @profile.profile_attributes.where(class_name: 'is_boss').pluck(:value)
      @selected_employee_classifications = @profile.profile_attributes.where(class_name: 'employee_classification').pluck(:value)
      @selected_companies = @profile.profile_attributes.where(class_name: 'company').pluck(:value)
      @selected_regions = @profile.profile_attributes.where(class_name: 'location_region').pluck(:value)
      @selected_benefit_groups = @profile.profile_attributes.where(class_name: 'benefit_group').pluck(:value)
      @selected_managements = @profile.profile_attributes.where(class_name: 'management').pluck(:value)
      @selected_cost_centers = @profile.profile_attributes.where(class_name: 'cost_center').pluck(:value)
      @selected_position_classifications = @profile.profile_attributes.where(class_name: 'position_classification').pluck(:value)
      @selected_syndicate_members = @profile.profile_attributes.where(class_name: 'syndicate_member').pluck(:value)
      @selected_contract_types = @profile.profile_attributes.where(class_name: 'contract_type').pluck(:value)
      @selected_roles = @profile.profile_attributes.where(class_name: 'rol').pluck(:value)
      @selected_schedules = @profile.profile_attributes.where(class_name: 'schedule').pluck(:value)
      @selected_has_children = @profile.profile_attributes.where(class_name: 'has_children').pluck(:value)
      @selected_office_countries = @profile.profile_attributes.where(class_name: 'office_country').pluck(:value)
      @selected_office_cities = @profile.profile_attributes.where(class_name: 'office_city').pluck(:value)
      @selected_office_regions = @profile.profile_attributes.where(class_name: 'office_region').pluck(:value)
    end

    def set_class_name_value(values, class_name)
      if values
        # Update
        values.each do |value|
          General::ProfileAttribute.where(class_name: class_name, profile_id: @profile.id).where.not(value: value).each(&:delete)
        end
        # Create
        values.each do |value|
          General::ProfileAttribute.where(class_name: class_name, value: value, profile_id: @profile.id).first_or_create
        end
      else
        General::ProfileAttribute.where(class_name: class_name, profile_id: @profile.id).each(&:delete)
      end
    end

    def set_profile
      @profile = General::Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :attached, regions: [], benefit_groups: [], companies: [], managements: [], genders: [], is_boss: [],
                                                        employee_classifications: [], cost_centers: [], position_classifications: [],
                                                        syndicate_members: [], contract_types: [], roles: [], schedules: [], has_childrens: [],
                                                        entry_dates: [], office_cities: [], office_countries: [], office_regions: [])
    end
  end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
<%= f.error_notification %>
<div class="form-group row">
  <div class="col-12">
    <h4 style="font-size: 16px; margin-top: 17px; font-weight: 700; font-style: italic;">
      Seleccione los filtros con los cuales desea crear el perfil.</h4>
  </div>
  <div class="col-12">
    <%= f.input :name, required: true, autofocus: true %>
  </div>
  <div class="col-12">
    <%= f.label 'Tipo de carga' %>
    <% selected_option = @profile.attached? ? "file" : "manual"%>
    <%= select_tag :creation_option, options_for_select([["Manual", "manual"], ["Archivo", "file"]], selected_option) %>
  </div>
</div>
<div id="file" style="display: none;">
  <div class="form-group row">
    <div class="col-12">
      <h5 style="font-size: 16px; margin-top: 17px; color: red;">
        El archivo debe ser de tipo Excel (xlsx). Los rut's de los usuarios deben estar en la primera columna, sin encabezado y sin guión.</h5>
    </div>
    <div class="col-12">
      <%= f.file_field "file"%>
    </div>
  </div>
</div>
<div id="manual_filters">
  <div class="form-group row">
    <% if false %>
      <div class="col-4">
        <%= f.label 'Sexo' %>
        <%= select_tag :genders, options_for_select(@genders, @selected_genders), multiple: true, class:' form-control string optional' %>
      </div>

      <div class="col-4">
        <%= f.label 'País de oficina' %>
        <%= select_tag :office_countries, options_for_select(@office_countries, @selected_office_countries), multiple: true, class:' form-control string optional' %>
      </div>
    <% end %>

    <div class="col-4">
      <%= f.label 'Pais oficina' %>
      <%= select_tag :countries, options_for_select(@countries.collect {|country| [country[1], country[0]]}, @selected_countries), multiple: true, class:' form-control string', id: 'countries' %>
    </div>

    <% if false %>
      <div class="col-4">
        <%= f.label 'Clasificación Empleado' %>
        <%= select_tag :employee_classifications, options_for_select(@employee_classifications, @selected_employee_classifications), multiple: true, class:' form-control string optional' %>
      </div>
      <div class="col-4">
        <%= f.label 'Empresas' %>
        <%= select_tag :companies, options_for_select(@companies.collect {|company| [company[1], company[0]]}, @selected_companies), multiple: true, class:' form-control string', id: 'companies' %>
      </div>
      <div class="col-4">
        <%= f.label 'Gerencias' %>
        <%= select_tag :managements, options_for_select(@managements.collect {|management| [management[1], management[0]]}, @selected_managements), multiple: true, class:' form-control string', id: 'managements' %>
      </div>
      <div class="col-4">
        <%= f.label 'Centro de Costos' %>
        <%= select_tag :cost_centers, options_for_select(@cost_centers.collect {|cost_center| [cost_center[1], cost_center[0]]}, @selected_cost_centers), multiple: true, class:' form-control string', id: 'cost_centers' %>
      </div>
      <div class="col-4">
        <%= f.label 'Clasificaciones de puesto' %>
        <%= select_tag :position_classifications, options_for_select(@position_classifications, @selected_position_classifications), multiple: true, class:' form-control string'%>
      </div>
      <div class="col-4">
        <%= f.label 'Tiene gente a cargo' %>
        <%= select_tag :is_boss, options_for_select(@is_boss, @selected_boss), multiple: true, class:' form-control string optional' %>
      </div>
      <div class="col-4">
        <%= f.label 'Ciudad de oficina' %>
        <%= select_tag :office_cities, options_for_select(@office_cities, @selected_office_cities), multiple: true, class:' form-control string optional' %>
      </div>
      <div class="col-4">
        <%= f.label 'Región de oficina' %>
        <%= select_tag :office_regions, options_for_select(@office_regions, @selected_office_regions), multiple: true, class:' form-control string optional' %>
      </div>
      <div class="col-4">
        <%= f.label 'Tiene hijos' %>
        <%= select_tag :has_children, options_for_select(@has_children, @selected_has_children), multiple: true, class:' form-control string' %>
      </div>
    <% end %>
  </div>
</div>
<div class="col-7">
</div>
<%= f.submit 'Guardar', :class => 'btn btn-primary mb-5', data: { disable_with: 'Guardando, espere un momento...' } %>

app/views/admin/profiles/edit.html.erb
<section class="section">
  <h1 class="section-header">Editar</h1>
  <%= simple_form_for @profile, as: 'profile', url: {action: :update}, :html => { :class => "form" } do |f| %>
    <%= render :partial => 'form', locals: {f: f} %>
  <% end %>
</section>

<!-- Modal -->
<div class="modal" id="loading" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-success" style="border: 1px solid black;">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-center">
          <%= image_tag("loading.gif", height: "50px") %>
        </div>
        <h5 class="modal-title text-center text-white mt-3" id="exampleModalLabel">
          Guardando, espere un momento... 
        </h5>
      </div>
    </div>
  </div>
</div>

<script>
  $('#edit_profile').submit(function(){
    $('#loading').show();
  });
</script>

app/views/admin/profiles/index.html.erb
<section class="section">
  <h1 class="section-header"><%= "Perfilamiento" %></h1>
  <%= link_to "Nuevo", new_admin_profile_path, :class => 'btn btn-primary btn-sm mb-1' %>
  <div class="card">
    <div class="table-responsive-md">
      <table class="table table-hover">
        <thead class="thead">
          <tr>
            <th><%= 'Estado' %></th>
            <th><%= 'Título' %></th>
            <th><%= 'Participantes' %></th>
            <th><%= 'Fecha Creación' %></th>
            <th><%= 'Acciones' %></th>
          </tr>
        </thead>
        <tbody>
          <% @profiles.each do |profile| %>
            <tr>
              <td><%= profile.id %></td>
              <td><%= profile.name %></td>
              <td><%= General::UserProfile.where(profile_id: profile.id).count %></td>
              <td><%= custom_date_no_hour(profile.created_at) %></td>
              <td>
                <%= link_to t('.show', :default => t("helpers.profiles.show")),
                              admin_profile_path(profile), :class => 'btn btn-success btn-sm' %>
                <%= link_to t('.edit', :default => t("helpers.profiles.edit")),
                              edit_admin_profile_path(profile), :class => 'btn btn-success btn-sm' %>
                <%= link_to 'Eliminar',
                              admin_profile_path(profile),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estás seguro?')) },
                              :class => 'btn btn-sm btn-danger'%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row justify-content-center">
      </div>
    </div>
  </div>
</section>

app/views/admin/profiles/new.html.erb
<section class="section">
  <h1 class="section-header">Crear Perfilamiento</h1>
  <%= simple_form_for @profile, as: 'profile', url: {action: :create}, :html => { :class => "form" } do |f| %>
    <%= render :partial => 'form', locals: {f: f} %>
  <% end %>
</section>
<!-- Modal -->
<div class="modal" id="loading" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-success" style="border: 1px solid black;">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-center">
          <%= image_tag("loading.gif", height: "50px") %>
        </div>
        <h5 class="modal-title text-center text-white mt-3" id="exampleModalLabel">
          Guardando, espere un momento... 
        </h5>
      </div>
    </div>
  </div>
</div>
<script>
  $('#new_profile').submit(function(){
    $('#loading').show();
  });
</script>

app/views/admin/profiles/show.html.erb
<section class="section">
  <h1 class="section-header">Nombre: <%= @profile.name %></h1>
  <div class="card">
    <div class="card-body">
      <div class="col-12">
        Oficinas:
        <ul>
          <% @office_countries.each do |country| %>
            <li><%= country.name %></li>
          <% end %>
        </ul>
      </div>
      <div>
        <%= link_to 'Descargar listado de usuarios', users_list_admin_profile_path(@profile, format: 'xlsx'), method: 'get'%>
      </div>
    </div>
  </div>
  <div>
    <%= link_to t('.back', :default => t("helpers.links.back")), admin_profiles_path, :class => 'btn btn-primary'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_profile_path(@profile), :class => 'btn btn-primary' %>
  </div>
</section>