config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: "General::User", controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  namespace :admin do
    post "upload", to: "attachments#upload"
    get "users/images_approbation", to: "users#images_approbation"
    get "analytics", to: "analytics#index"
    get "search", to: "search#search"
    
    resources :profiles do
      get :users_list, on: :member
    end

    resources :users

    resources :helpcenter_questions do
      get :subcategories, on: :collection
    end
    resources :helpcenter_categories do
      get :assistants, on: :member
    end
    resources :helpcenter_tickets do
      get :subcategories, on: :collection
      put :take_ticket, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      resources :helpcenter_messages, on: :member, only: [:create]
      get :tickets_list, on: :member
    end
    resources :expense_report_requests do
      put :take_request, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      get :requests_list, on: :member
      get :download_request_pdf, on: :member

    end
    resources :expense_report_categories 
    resource :chat_messages
    resource :chat_rooms

    root to: "helpcenter_tickets#index"
  end

  namespace :api, :defaults => { :format => "json" } do
    namespace :v1, :defaults => { :format => "json" } do
      resources :users, only: [:show] do
        post :sign_in, on: :collection
        delete :sign_out, on: :collection
        get :current_user_vue, on: :collection
      end

      post 'users', to: 'users#create_update'
      delete 'users', to: 'users#destroy'
      get 'search/users', to: 'users#search'

      get 'societies', to: 'societies#societies'
      get 'categories', to: 'expense_report_categories#categories' 
      
      resources :hc_questions, only: [:show] do
        get :importants, on: :collection
        get :search, on: :collection
      end
      post 'expense_report_requests/review_request', to: 'expense_report_requests#review_request' 
      get 'expense_report_requests/response_request', to: 'expense_report_requests#response_request' 
      get 'expense_report_requests/divisas', to: 'expense_report_requests#divisas'
      get 'expense_report_requests/countries', to: 'expense_report_requests#countries'
      get 'expense_report_requests/accounts', to: 'expense_report_requests#accounts'
      get 'expense_report_requests/payment_method', to: 'expense_report_requests#payment_method'
      post 'expense_report_requests/save_draft_request', to: 'expense_report_requests#save_draft_request'
      get 'expense_report_requests/request_draft', to: 'expense_report_requests#request_draft'
      get 'expense_report_requests/request_user', to: 'expense_report_requests#request_user'
      get 'expense_report_requests/pending_requests', to: 'expense_report_requests#pending_requests'
      resources :expense_report_requests do
        delete :destroy_file, on: :collection
        delete :destroy_invoice, on: :collection
      end
      resources :chat_messages, param: :slug, only: [:create]
      
      resources :hc_categories, param: :slug, only: [:index, :show]
      resources :hc_subcategories, param: :slug, only: [:show]
      
      resources :hc_tickets do
        get :divisas, on: :collection
        get :ofertas, on: :collection
        resources :hc_messages, on: :member, only: [:create]
        resources :hc_satisfaction_answers, on: :member, only: [:create]
        post :create_postulacion, on: :member
        get :index_job_applications, on: :collection
        patch :update_postulacion_status, on: :member
        put :assign_assistant, on: :member
      end
    end
    
    root to: "application#index"
  end

  root to: "application#index"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
module Chat
  def self.table_name_prefix
    'chat_'
  end
end

app/models/company.rb
module Company
  def self.table_name_prefix
    "company_"
  end
end

app/models/employee.rb
module Employee
  def self.table_name_prefix
    "employee_"
  end
end

app/models/expense_report.rb
module ExpenseReport
  def self.table_name_prefix
    'expense_report_'
  end
end

app/models/general.rb
module General
  def self.table_name_prefix
    "general_"
  end
end

app/models/helpcenter.rb
module Helpcenter
  def self.table_name_prefix
    'helpcenter_'
  end
end

app/models/library.rb
module Library
  def self.table_name_prefix
    'library_'
  end
end

app/models/location.rb
module Location
  def self.table_name_prefix
    "location_"
  end
end

app/models/marketplace.rb
module Marketplace
  def self.table_name_prefix
    "marketplace_"
  end
end

app/models/media.rb
module Media
  def self.table_name_prefix
    "media_"
  end
end

app/models/menu.rb
module Menu
  def self.table_name_prefix
    'menu_'
  end
end

app/models/news.rb
module News
  def self.table_name_prefix
    "news_"
  end
end

app/models/payment.rb
module Payment
  def self.table_name_prefix
    'payment_'
  end
end

app/models/personal_data.rb
module PersonalData
  def self.table_name_prefix
    'personal_data_'
  end
end

app/models/religion.rb
module Religion
  def self.table_name_prefix
    "religion_"
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :general_users, :join_table => :general_users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/survey.rb
module Survey
  def self.table_name_prefix
    "survey_"
  end
end

app/controllers/admin/helpcenter_categories_controller.rb
module Admin
  class HelpcenterCategoriesController < AdminController
    before_action :set_category, only: [:edit, :show, :destroy, :update, :assistants]
    before_action :check_admin

    def index
      if current_user.has_role? :admin
        @categories = Helpcenter::Category.all
      else
        @categories = current_user.help_categories
      end
    end

    def new
      @category = Helpcenter::Category.new
    end

    def edit
      
    end

    def show

    end

    def create
      @category = Helpcenter::Category.new(category_params)

      respond_to do |format|
        if @category.save
          Role.create(name: @category.name, resource: @category)
          format.html { redirect_to admin_helpcenter_category_path(@category), notice: 'Categoría fue creada con éxito.' }
          format.json { render :show, status: :created, location: @category }
          format.js
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end

    def update
      respond_to do |format|
        if @category.update(category_params)
          Role.find_by(resource: @category).update(name: @category.name)
          format.html { redirect_to admin_helpcenter_category_path(@category), notice: 'Categoría fue actualizada con éxito.' }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      respond_to do |format|
        if @category.destroy
          @category.roles.delete_all
          format.html { redirect_to admin_helpcenter_categories_path, notice: 'Categoría fue eliminada con éxito.' }
        else
          format.html { redirect_to admin_helpcenter_categories_path, notice: 'Algo salió mal' }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    def assistants

    end

    private

    def set_category
      @category = Helpcenter::Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(
        :name, 
        :slug, 
        :image,
        :profile_id,
        subcategories_attributes: [:id, :name, :_destroy]
      )
    end
  end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/admin/helpcenter_categories/_form.html.erb
<%= f.error_notification category: f.object.errors[:category].to_sentence%>

<%= f.error_notification %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="col-md-12">
          <%= f.input :name, autofocus: true, input_html: { class: "border border-dark" } %>
        </div>
        <div class="col-12 col-sm-12 mb-3">
          <% selected_value = @category.profile_id || General::Profile.first.id %>
          <%= f.label :profile %>
          <%= f.select :profile_id, options_for_select(General::Profile.all.map{|profile| [profile.name, profile.id]}, selected_value), {} %>
        </div>
      </div>
      <div class="col-md-12">
        <h2 class="text-center"><%= "Lista de sub-categorías" %></h2>
      </div>
      <div class="col-md-12 card" id="subcategories">
        <%= f.simple_fields_for :subcategories do |subcategory_form|%>
          <%= render 'subcategory_fields', f: subcategory_form %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card row">
        <div class="col-md-12">
          <%= f.label "Imagen" %>
          <div class="card border-secondary border border-primary rounded">
            <div class="card-body text-secondary text-md-center">
              <% if @category.image.attachment.present? %>
                <%= image_tag(@category.image.variant(resize: '100x100>'), class: 'py-4') %>
              <% end %>
              <div class="left">
                <%= f.file_field :image, multiple: false, as: :file, input_html: { accept:'image/*' }, onchange: "validateImage('benefit_image')" %>
              </div>
              <div class="tip_format">
                * Las dimensiones de la imágen deben ser de 48px x 48px
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to_add_association "Agregar sub-categoría", 
          f, :subcategories, 
          class: 'btn btn-success buttons_group', 
          data: {
            association_insertion_node: '#subcategories', 
            association_insertion_method: :append 
          } 
      %>
    <div>
  </div>
</div>

app/views/admin/helpcenter_categories/assistants.html.erb
<div class="container">
  <section class="section">
    <h2 class="section-header"><%= @category.name %></h2>

    <div class="container card">
      <div class="col-md-12" align="center">
        <h4>Assistentes:</h4>
        <div class="table-responsive-md">
          <table class="table table-hover">
            <thead class="thead">
              <tr>
                <th><%= "Nombre" %></th>
                <th><%= "Promedio tiempo" %></th>
              </tr>
            </thead>
            <tbody>
              <% @category.assistants.order(:id).each do |assistant| %>
                <tr>
                  <td><%= assistant.full_name %></td>
                  <td><%= assistant.average_time %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="container" align="center">
      <%= link_to t("helpers.links.back"), admin_helpcenter_categories_path, :class => 'btn btn-primary'  %>
      <%= link_to t("helpers.links.edit"), edit_admin_helpcenter_category_path(@category), :class => 'btn btn-primary' %>
    </div>
  </section>
</div>

app/views/admin/helpcenter_categories/edit.html.erb
<section class="section">
  <h1 class="section-header"><%= "Editar" %>: <%= @category.name %></h1>
  <%= simple_form_for @category, as: 'category', url: {action: :update}, :html => { :class => "form" } do |f| %>
    <%= render :partial => 'form', locals: {f: f} %>
  <% end %>
</section>

app/views/admin/helpcenter_categories/index.html.erb
<section class="section">
  <h1 class="section-header"><%= "Categorías" %></h1>
  <%= link_to "Nuevo", new_admin_helpcenter_category_path, class: 'btn btn-primary btn-sm mb-1' %>
  <div class="card">
    <div class="table-responsive-md">
      <table class="table table-hover" id="categories_table">
        <thead class="thead">
          <tr>
            <th><%= 'Icono' %></th>
            <th><%= "Nombre" %></th>
            <th><%= 'Oficina' %></th>
            <th><%= "Acciones" %></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= image_tag category.image.attachment.variant(resize: '30x30!'), :class=> 'img-thumbnail img-fluid' unless category.image.attachment.nil? %></td>
              <td><%= category.name %></td>
              <td><%= category.profile.name %></td>
              <td>
                
                <%= link_to t("helpers.links.show"),
                              admin_helpcenter_category_path(category), :class => 'btn btn-success btn-xs' %>
                <%= link_to t("helpers.links.edit"),
                              edit_admin_helpcenter_category_path(category), :class => 'btn btn-primary btn-xs' %>

                <%= link_to "Resolutores",
                assistants_admin_helpcenter_category_path(category), :class => 'btn btn-success btn-xs' %>

                <%= link_to t("helpers.links.destroy"),
                              admin_helpcenter_category_path(category),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.messages.confirm", :default => '¿Esta segura(o) que desea eliminar este elemento?')) },
                              :class => 'btn btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row justify-content-center">
      </div>
    </div>
  </div>
</section>

app/views/admin/helpcenter_categories/show.html.erb
<div class="container">
  <section class="section">
    <h2 class="section-header"><%= @category.name %></h2>
    <div class="container">
      <div class="row card">
        <div class="col-12 mt-4" align="center">
          <%=image_tag @category.image.variant(resize: "100x100>") if @category.image.attached? %>
        </div>
        <div class="col-sm-12 mt-4">
          <p>
            <b><%= "Nombre" %>:</b> <%= @category.name %>
          </p>
        </div>
      </div>
    </div>

    <div class="container card">
      <div class="col-md-12" align="center">
        <h4>Sub-categorías:</h4>
        <div class="table-responsive-md">
          <table class="table table-hover">
            <thead class="thead">
              <tr>
                <th><%= "Nombre" %></th>
              </tr>
            </thead>
            <tbody>
              <% @category.subcategories.order(:id).each do |subcat| %>
                <tr>
                  <td><%= subcat.name %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="container" align="center">
      <%= link_to t("helpers.links.back"), admin_helpcenter_categories_path, :class => 'btn btn-primary'  %>
      <%= link_to t("helpers.links.edit"), edit_admin_helpcenter_category_path(@category), :class => 'btn btn-primary' %>
    </div>
  </section>