config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: "General::User", controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  namespace :admin do
    post "upload", to: "attachments#upload"
    get "users/images_approbation", to: "users#images_approbation"
    get "analytics", to: "analytics#index"
    get "search", to: "search#search"
    
    resources :profiles do
      get :users_list, on: :member
    end

    resources :users

    resources :helpcenter_questions do
      get :subcategories, on: :collection
    end
    resources :helpcenter_categories do
      get :assistants, on: :member
    end
    resources :helpcenter_tickets do
      get :subcategories, on: :collection
      put :take_ticket, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      resources :helpcenter_messages, on: :member, only: [:create]
      get :tickets_list, on: :member
    end
    resources :expense_report_requests do
      put :take_request, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      get :requests_list, on: :member
      get :download_request_pdf, on: :member

    end
    resources :expense_report_categories 
    resource :chat_messages
    resource :chat_rooms

    root to: "helpcenter_tickets#index"
  end

  namespace :api, :defaults => { :format => "json" } do
    namespace :v1, :defaults => { :format => "json" } do
      resources :users, only: [:show] do
        post :sign_in, on: :collection
        delete :sign_out, on: :collection
        get :current_user_vue, on: :collection
      end

      post 'users', to: 'users#create_update'
      delete 'users', to: 'users#destroy'
      get 'search/users', to: 'users#search'

      get 'societies', to: 'societies#societies'
      get 'categories', to: 'expense_report_categories#categories' 
      
      resources :hc_questions, only: [:show] do
        get :importants, on: :collection
        get :search, on: :collection
      end
      post 'expense_report_requests/review_request', to: 'expense_report_requests#review_request' 
      get 'expense_report_requests/response_request', to: 'expense_report_requests#response_request' 
      get 'expense_report_requests/divisas', to: 'expense_report_requests#divisas'
      get 'expense_report_requests/countries', to: 'expense_report_requests#countries'
      get 'expense_report_requests/accounts', to: 'expense_report_requests#accounts'
      get 'expense_report_requests/payment_method', to: 'expense_report_requests#payment_method'
      post 'expense_report_requests/save_draft_request', to: 'expense_report_requests#save_draft_request'
      get 'expense_report_requests/request_draft', to: 'expense_report_requests#request_draft'
      get 'expense_report_requests/request_user', to: 'expense_report_requests#request_user'
      get 'expense_report_requests/pending_requests', to: 'expense_report_requests#pending_requests'
      resources :expense_report_requests do
        delete :destroy_file, on: :collection
        delete :destroy_invoice, on: :collection
      end
      resources :chat_messages, param: :slug, only: [:create]
      
      resources :hc_categories, param: :slug, only: [:index, :show]
      resources :hc_subcategories, param: :slug, only: [:show]
      
      resources :hc_tickets do
        get :divisas, on: :collection
        get :ofertas, on: :collection
        resources :hc_messages, on: :member, only: [:create]
        resources :hc_satisfaction_answers, on: :member, only: [:create]
        post :create_postulacion, on: :member
        get :index_job_applications, on: :collection
        patch :update_postulacion_status, on: :member
        put :assign_assistant, on: :member
      end
    end
    
    root to: "application#index"
  end

  root to: "application#index"
end

app/controllers/admin/helpcenter_tickets_controller.rb
module Admin
  class HelpcenterTicketsController < AdminController
    before_action :set_ticket, only: [:edit, :show, :destroy, :update, :take_ticket, :close]
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def index
      @status = params[:status]

      respond_to do |format|
        format.html
        format.json { render json: TicketsDatatable.new(view_context) }
      end
    end

    def new
      @ticket = Helpcenter::Ticket.new
      @users = General::User.all.map { |u| [u.full_name, u.id] }
      @subcategories = []
    end

    def tickets_list
      @tickets = Helpcenter::Ticket.all
      render xlsx: 'tickets_list.xlsx.axlsx', filename: "listada de tickets #{Date.today}.xlsx"
    end

    def edit
      authorize @ticket, :show?
      @users = General::User.all.map { |u| [u.full_name, u.id] }
      # @subcategories = Helpcenter::Subcategory.where(category: @ticket.subcategory.category)
    end

    def create
      @users = General::User.all.map { |u| [u.full_name, u.id] }
      @ticket = Helpcenter::Ticket.new(ticket_params)
      @ticket.created_by_admin = true

      respond_to do |format|
        if @ticket.save
          Helpcenter::TicketHistory.create(user_id: current_user.id, ticket_id: @ticket.id, ticket_state_id: Helpcenter::TicketState.find_by(status: "open").id)
          format.html { redirect_to admin_helpcenter_ticket_path(@ticket), notice: "Ticket fue creado con éxito." }
          format.json { render :show, status: :ok, location: @ticket }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    def show
      authorize @ticket, :show?
      @user = General::User.with_deleted.find(@ticket.user_id)
      @message = Helpcenter::Message.new
      @messages = @ticket.chat_messages
      @supervisor = General::User.where(id_exa: @user.id_exa_boss).last.try(:full_name)
      @resolutors = General::User.includes(:roles).where(roles: { name: 'resolutor' }).references(:roles)
    end

    def take_ticket
      result = Helpcenter::Ticket.take_ticket(params[:take_ticket], @ticket, current_user)
      @ticket = result[:ticket]
      respond_to do |format|
        if result[:success] == true
          format.html { redirect_to admin_helpcenter_ticket_path(@ticket), notice: "Ticket fue actualizado con éxito." }
          format.json { render :show, status: :ok, location: @ticket }
        else
          format.html { redirect_to admin_helpcenter_ticket_path(@ticket), notice: "Ocurrió un error" }
          format.json { render :show, status: :ok, location: @ticket }
        end
      end
    end

    def close
      respond_to do |format|
        if @ticket.update(closed_at: DateTime.now, status: Helpcenter::TicketState.find_by(status: "closed").status)
          Helpcenter::TicketHistory.create(user_id: current_user.id, ticket_id: @ticket.id, ticket_state_id: Helpcenter::TicketState.find_by(status: "closed").id)
          # UserNotifierMailer.notification_ticket_close(@ticket).deliver
          format.html { redirect_to admin_helpcenter_ticket_path(@ticket), notice: "Ticket fue actualizado con éxito." }
          format.json { render :show, status: :ok, location: @ticket }
        else
          format.html { redirect_to admin_helpcenter_ticket_path(@ticket), notice: "Ocurrió un error" }
          format.json { render :show, status: :ok, location: @ticket }
        end
      end
    end

    def update
      authorize @ticket, :show?
      respond_to do |format|
        if @ticket.update(ticket_params)
          format.html { redirect_to admin_helpcenter_ticket_path(@ticket), notice: "Ticket fue actualizado con éxito." }
          format.json { render :show, status: :ok, location: @ticket }
        else
          format.html { redirect_to admin_helpcenter_ticket_path(@ticket), notice: "Ocurrió un error" }
          format.json { render :show, status: :ok, location: @ticket }
        end
      end
    end

    def destroy
      Helpcenter::TicketHistory.create(user_id: current_user.id, ticket_id: @ticket.id, ticket_state_id: Helpcenter::TicketState.find_by(status: "deleted").status)
      @ticket.destroy
      respond_to do |format|
        format.html { redirect_to admin_helpcenter_tickets_path, notice: "Ticket fue eliminado con éxito." }
        format.json { head :no_content }
      end
    end

    def subcategories
      @subcategories = Helpcenter::Subcategory.where(category_id: params[:category_id])
      render :partial => "admin/helpcenter_tickets/subcategories", :object => @subcategories
    end

    def inbox
      @status = params[:status]

      respond_to do |format|
        format.html
        format.json { render json: InboxTicketsDatatable.new(view_context) }
      end
    end

    private

    def user_not_authorized
      redirect_to(admin_helpcenter_tickets_path)
    end

    def set_ticket
      @ticket = Helpcenter::Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:name, :description, :subcategory_id, :user_id, :character_of_process, :recruitment_source, :reason_for_search, :number_of_vacancies, :area, :company, :required_education, :cost_center, :careers, :years_of_experience, :job_location, :work_schedule, :shift, :observation, :admission_date, :income_composition, :requires_account, :requires_computer, :request_date, :requested_position_title, :replacement_user_id, files: [])
    end
  end
end

app/views/admin/helpcenter_tickets/_assign_modal.html.erb
<div class="modal fade" id="assignModal" tabindex="-1" role="dialog" aria-labelledby="assignModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="assignModalLabel">Asignar Caso</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_with(model: @ticket, url: assign_assistant_api_v1_hc_ticket_path(@ticket), method: :put, local: true) do |form| %>
            <div class="form-group">
              <%= form.label :assistant_id, "Seleccione un Asistente:" %>
              <%= form.collection_select :assistant_id, General::User.all, :id, :full_name, {include_blank: true}, {class: 'form-control'} %>
            </div>
            <%= form.submit "Asignar", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  

  <style>

.modal-backdrop {
          z-index: 1040; /* Valor menor */
      }

      .modal {
          z-index: 1050; /* Valor mayor */
      }
      .modal-content {
    opacity: 1 !important; /* Asegura opacidad total */
    background-color: #FFF; /* Fondo blanco o el que desees */
}
  </style>

app/views/admin/helpcenter_tickets/_subcategories.js.erb
$('#ticket_subcategory_id').empty();
$('#ticket_subcategory_id').append( $('<option>Selecciona una subcategoría</option>'));
$("#ticket_subcategory_id").prop("disabled", false);
<% @subcategories.each do |subcat| %>
  $('#ticket_subcategory_id').append($('<option value="<%= subcat.id %>"><%= subcat.name %></option>'));
<% end %>

app/views/admin/helpcenter_tickets/edit.html.erb
<section class="section">
  <h1 class="section-header"><%= "Editar" %>: <%= "Ticket ##{@ticket.id}" %></h1>
  <%= simple_form_for @ticket, as: 'ticket', url: {action: :update}, :html => { :class => "form" } do |f| %>
    <%= render :partial => 'form', locals: {f: f} %>
  <% end %>
</section>

app/views/admin/helpcenter_tickets/inbox.html.erb
<section class="section">
  <h1 class="section-header"><%= "Inbox" %></h1>

  <%= link_to "Nuevo", new_admin_helpcenter_ticket_path, class: 'btn btn-primary btn-sm mb-1' if current_user.is_admin? %>

  <div class="card mb-0">
    <%= form_tag('', method: 'get') do %>
      <div class="large-12 columns">
        <div class="row">
          <div class="row" style='margin-left: 10px;padding: 15px;'>
            <%= select_tag(
                :status, 
                options_for_select(Helpcenter::Ticket::STATUS_COLLECTION.map{ |a| [a[1], a[0]] } ), 
                include_blank: 'Seleccionar', 
                class: 'custom-select',
                :onchange => 'ticket_filter_action()') 
            %>
            <%= button_tag "Buscar", class: "btn btn-primary btn-sm", id: 'ticket_filter', style: 'display: none' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="card">
    <div class="table-responsive-md">
      <table data-order='[[ 0, "desc" ]]' class="table table-hover" id="inbox_tickets_table" data-source="<%= inbox_admin_helpcenter_tickets_path(status: @status, format: :json) %>">
        <thead class="thead">
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</section>

<script>
  function ticket_filter_action() {
    document.getElementById("ticket_filter").click()
  }
</script>

app/views/admin/helpcenter_tickets/index.html.erb
<section class="section">
  <h1 class="section-header"><%= "Proceso de Selección" %></h1>
  <% if current_user.is_admin?%>
    <div>
      <%= link_to "Nueva Solicitud", new_admin_helpcenter_ticket_path, class: 'btn btn-primary mb-1'%>
      <%= link_to 'Descargar listado solicitudes', tickets_list_admin_helpcenter_ticket_path(:helpcenter_ticket_id,format: 'xlsx'), method: 'get', class:'btn btn-primary mb-1'%>
    </div>
  <% end %>
  <div class="card mb-0">
    <%= form_tag('', method: 'get') do %>
      <div class="large-12 columns">
        <div class="row">
          <div class="row" style='margin-left: 10px;padding: 15px;'>
            <%= select_tag(
                :status, 
                options_for_select(Helpcenter::Ticket::STATUS_COLLECTION.map{ |a| [a[1], a[0]] } ), 
                include_blank: 'Seleccionar', 
                class: 'custom-select',
                :onchange => 'ticket_filter_action()') 
            %>
            <%= button_tag "Buscar", class: "btn btn-primary btn-sm", id: 'ticket_filter', style: 'display: none' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="card">
    <div class="table-responsive-md">
      <table data-order='[[ 0, "desc" ]]' class="table table-hover" id="tickets_table" data-source="<%= admin_helpcenter_tickets_path(status: @status, format: :json) %>">
        <thead class="thead">
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</section>

<script>
  function ticket_filter_action() {
    document.getElementById("ticket_filter").click()
  }
</script>

app/views/admin/helpcenter_tickets/new.html.erb
<section class="section">
  <h1 class="section-header"><%= "Nueva Solicitud" %></h1>
  <%= simple_form_for @ticket, as: 'ticket', url: {action: :create}, :html => { :class => "form" } do |f| %>
    <%= render :partial => 'form', locals: {f: f} %>
  <% end %>
</section>

app/views/admin/helpcenter_tickets/show.html.erb
<div class="container">
  <section class="section">
    <h2 class="section-header">Caso # <%= @ticket.id %> - <%= t("ticket.status.#{@ticket.status}") %></h2>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="card post_card">
            <div class="card-header">
              <h3 class="card-title">Detalle de Selección</h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-6">
                  <p><strong>Nombre del solicitante:</strong> <%= @ticket.user.full_name if @ticket.user %></p>
                  <p><strong>Cargo del solicitante:</strong> <%= @ticket&.user&.position || 'No definido' %></p>
                  <p><strong>Carácter del Proceso:</strong> <%= @ticket.character_of_process.humanize %></p>
                  <p><strong>Fuente de Reclutamiento:</strong> <%= @ticket.recruitment_source.humanize %></p>
                  <p><strong>Fecha de solicitud:</strong> <%= @ticket.request_date.strftime('%d/%m/%Y') %></p>
                  <p><strong>Posición solicitada:</strong> <%= @ticket.requested_position_title.humanize %></p>
                  <p><strong>Motivo de búsqueda:</strong> <%= @ticket.reason_for_search.humanize %></p>
                  <p><strong>Nombre de colaborador a reemplazar:</strong> <%= @ticket.replacement_user&.full_name || 'No definido'%></p>
                  <p><strong>Número de vacantes:</strong> <%= @ticket.number_of_vacancies %></p>
                  <p><strong>Área:</strong> <%= @ticket.area.humanize %></p>
                  <p><strong>Empresa:</strong> <%= @ticket.company.humanize %></p>
                  <p><strong>Centro de costo:</strong> <%= @ticket.cost_center %></p>
                </div>
                <div class="col-6">
                  <p><strong>Formación Académica requerida:</strong> <%= @ticket.required_education.humanize %></p>
                  <p><strong>Carrera:</strong> <%= @ticket.careers%></p> 
                  <p><strong>Años de experiencia:</strong> <%= @ticket.years_of_experience %></p>
                  <p><strong>Ubicación física del cargo:</strong> <%= @ticket.job_location.humanize %></p>
                  <p><strong>Horario de trabajo:</strong> <%= @ticket.work_schedule.humanize %></p>
                  <p><strong>Turno:</strong> <%= @ticket.shift.humanize %></p>
                  <p><strong>Requiere Computador:</strong> <%= @ticket.requires_computer.humanize %></p>
                  <p><strong>Requiere Cuenta:</strong> <%= @ticket.requires_account.humanize %></p>
                  <p><strong>Fecha de ingreso máxima:</strong> <%= @ticket.admission_date.strftime('%d/%m/%Y') %></p>
                  <p><strong>Composición de la renta:</strong> <%= @ticket.income_composition.humanize %></p>
                  <p><strong>Observaciones:</strong> <%= @ticket.observation %></p>
                </div>
                <br>
                <div class="col-12 my-4">
    
                  <h4>Asignar Caso </h4>
                  <%= form_with model: @ticket, url: assign_assistant_api_v1_hc_ticket_path(@ticket), method: :put, local: true do |form| %>
                    <div class="form-group">
                      <%= form.label :assistant_id, "Seleccione un Asistente:" %>
                      <%= form.collection_select :assistant_id, @resolutors, :id, :full_name, {include_blank: true}, {class: 'form-control'} %>
                    </div>
                    <%= form.submit "Actualizar", class: "btn btn-primary" %>
                  <% end %>
                </div>
                <div class="col-12 my-4">
                  <h2>Postulantes:  <span><%= @ticket&.postulaciones&.count%></span> </h2>
                  <% if @ticket.postulaciones.exists? %>
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Nombre del Candidato</th>
                          <th>Email</th>
                          <th>Teléfono</th>
                          <th>Estado de Postulación</th>
                          <th>Currículum</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @ticket.postulaciones.each do |postulacion| %>
                        <tr>
                          <td><%= postulacion.applicant_name %></td>
                          <td><%= postulacion.email %></td>
                          <td><%= postulacion.phone %></td>
                          <td>
                            <%= form_with(model: [ @ticket, postulacion ], url: update_postulacion_status_api_v1_hc_ticket_path(@ticket, postulacion_id: postulacion.id), method: :patch, local: true) do |form| %>
                              <%= form.select :application_status, options_for_select(Helpcenter::JobApplication.application_statuses.map { |key, value| [key.humanize, key] }, postulacion.application_status), {}, { onchange: "this.form.submit();" } %>
                            <% end %>
                          </td>
                          <td>
                            <%= link_to "Descargar", rails_blob_path(postulacion.file, disposition: "attachment") if postulacion.file.attached? %>
                          </td>
                        </tr>
                      <% end %>
                      </tbody>
                    </table>
                  <% else %>
                    <p>No hay postulantes para este caso.</p>
                  <% end %>
                </div>                
              </div>
            </div>
            <!-- <div class="card post_card">
              <div class="card-header">
                <h3 class="card-title">Archivos adjuntos: <%= @ticket.files.count %></h3>
              </div>
              <div class="card-body">
                <ul class="list-group list-group-flush">
                  <% @ticket.files.each_with_index do |file, i| %>
                    <li class="list-group-item">
                      <%= link_to "#{i + 1}) #{file.filename.to_s}", root_url + rails_blob_path(file, disposition: "attachment")%>
                    </li>
                  <% end %>
                </ul>
              </div>
              <div class="col-12">
              </div>
            </div> -->
          </div>
          <!-- <% if @ticket.assistant == current_user %>
            <div class="col-md-12">
              <div class="msg_history">
                <% @messages.each do |message| %>
                  <% if message.user == current_user %>
                    <div class="outgoing_msg">
                      <div class="sent_msg">
                        <p><%= message.content %></p>
                        <span class="time_date"> <%= message.format_created_at %></span>
                      </div>
                    </div>
                  <% else %>
                    <div class="incoming_msg">
                      <div class="received_msg">
                        <div class="received_withd_msg">
                          <p><%= message.content %></p>
                          <span class="time_date"> <%= message.format_created_at %></span>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <% if @ticket.closed_at.nil? %>
                <div class="col-md-12">
                  <div class="type_msg">
                    <div class="col-md-12 input_msg_write">
                      <%= form_with url: admin_helpcenter_ticket_helpcenter_messages_path(@ticket), method: :post, model: @message do |f| %>
                        <div class="row">
                          <div class="col-md-9">
                            <%= f.text_field :content, required: true, class: "write_msg", placeholder: "Ingresa una respuesta..." %>
                          </div>
                          <div class="col-md-3">
                            <button type="submit" class="btn btn-primary">Responder</button>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div> -->
          <br />
          <div class="container mt-5" align="center">
            <%= link_to t("helpers.links.back"), admin_helpcenter_tickets_path, :class => 'btn btn-primary'  %>
            <%= link_to "#{current_user.is_admin? ? 'Editar' : 'Recategorizar'}", edit_admin_helpcenter_ticket_path(@ticket), :class => 'btn btn-primary' %>
            <% if @ticket.assistant == current_user %>
              <%= link_to "Dejar caso", take_ticket_admin_helpcenter_ticket_path(@ticket, take_ticket: false), method: :put, class: 'btn btn-primary' if @ticket.closed_at.nil? %>
              <%= link_to "Marcar como resuelto",  close_admin_helpcenter_ticket_path(@ticket), method: :put, class: 'btn btn-primary' if @ticket.closed_at.nil? %>
            <% end %>
            <% if @ticket.assistant.nil? && current_user.is_resolutor? %>
              <%= link_to "Tomar caso", take_ticket_admin_helpcenter_ticket_path(@ticket, take_ticket: true), method: :put, class: 'btn btn-primary' %>
            <% end %>

            <% if @ticket&.status != 'closed' && current_user.is_admin? %>
              <%= link_to "Asignar Caso", "#assignModal", class: 'btn btn-primary', data: { toggle: 'modal' } %>
            <% end %>

          </div>
        </div>
      </section>
    </div>
    <style>
      .chat_people{ overflow:hidden; clear:both;}
      .chat_list {
        border-bottom: 1px solid #c4c4c4;
        margin: 0;
        padding: 18px 16px 10px;
      }
      .inbox_chat { height: 550px; overflow-y: scroll;}

      .active_chat{ background:#ebebeb;}

      .incoming_msg_img {
        display: inline-block;
        width: 6%;
      }
      .received_msg {
        display: inline-block;
        padding: 0 0 0 10px;
        vertical-align: top;
        width: 92%;
       }
       .received_withd_msg p {
        background: #ebebeb none repeat scroll 0 0;
        border-radius: 3px;
        color: #646464;
        font-size: 14px;
        margin: 0;
        padding: 5px 10px 5px 12px;
        width: 100%;
      }
      .time_date {
        color: #747474;
        display: block;
        font-size: 12px;
        margin: 8px 0 0;
      }
      .received_withd_msg { width: 57%;}
      .mesgs {
        float: left;
        padding: 30px 15px 0 25px;
        width: 60%;
      }

       .sent_msg p {
        background: #05728f none repeat scroll 0 0;
        border-radius: 3px;
        font-size: 14px;
        margin: 0; color:#fff;
        padding: 5px 10px 5px 12px;
        width:100%;
      }
      .outgoing_msg{ overflow:hidden; margin:26px 0 26px;}
      .sent_msg {
        float: right;
        width: 46%;
      }
      .input_msg_write input {
        background: rgba(0, 0, 0, 0) scroll 0 0;
        border: 1px solid;
        color: #4c4c4c;
        font-size: 15px;
        min-height: 48px;
        width: 100%;
      }

      .type_msg {border-top: 1px solid #c4c4c4;position: relative; padding-top: 20px;}
      .msg_send_btn {
        background: #05728f none repeat scroll 0 0;
        border: medium none;
        border-radius: 50%;
        color: #fff;
        cursor: pointer;
        font-size: 17px;
        height: 33px;
        position: absolute;
        right: 0;
        top: 11px;
        width: 33px;
      }

      .msg_history {
        height: 516px;
        overflow-y: auto;
      }