config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: "General::User", controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  namespace :admin do
    post "upload", to: "attachments#upload"
    get "users/images_approbation", to: "users#images_approbation"
    get "analytics", to: "analytics#index"
    get "search", to: "search#search"
    
    resources :profiles do
      get :users_list, on: :member
    end

    resources :users

    resources :helpcenter_questions do
      get :subcategories, on: :collection
    end
    resources :helpcenter_categories do
      get :assistants, on: :member
    end
    resources :helpcenter_tickets do
      get :subcategories, on: :collection
      put :take_ticket, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      resources :helpcenter_messages, on: :member, only: [:create]
      get :tickets_list, on: :member
    end
    resources :expense_report_requests do
      put :take_request, on: :member
      put :close, on: :member
      get :inbox, on: :collection
      get :requests_list, on: :member
      get :download_request_pdf, on: :member

    end
    resources :expense_report_categories 
    resource :chat_messages
    resource :chat_rooms

    root to: "helpcenter_tickets#index"
  end

  namespace :api, :defaults => { :format => "json" } do
    namespace :v1, :defaults => { :format => "json" } do
      resources :users, only: [:show] do
        post :sign_in, on: :collection
        delete :sign_out, on: :collection
        get :current_user_vue, on: :collection
      end

      post 'users', to: 'users#create_update'
      delete 'users', to: 'users#destroy'
      get 'search/users', to: 'users#search'

      get 'societies', to: 'societies#societies'
      get 'categories', to: 'expense_report_categories#categories' 
      
      resources :hc_questions, only: [:show] do
        get :importants, on: :collection
        get :search, on: :collection
      end
      post 'expense_report_requests/review_request', to: 'expense_report_requests#review_request' 
      get 'expense_report_requests/response_request', to: 'expense_report_requests#response_request' 
      get 'expense_report_requests/divisas', to: 'expense_report_requests#divisas'
      get 'expense_report_requests/countries', to: 'expense_report_requests#countries'
      get 'expense_report_requests/accounts', to: 'expense_report_requests#accounts'
      get 'expense_report_requests/payment_method', to: 'expense_report_requests#payment_method'
      post 'expense_report_requests/save_draft_request', to: 'expense_report_requests#save_draft_request'
      get 'expense_report_requests/request_draft', to: 'expense_report_requests#request_draft'
      get 'expense_report_requests/request_user', to: 'expense_report_requests#request_user'
      get 'expense_report_requests/pending_requests', to: 'expense_report_requests#pending_requests'
      resources :expense_report_requests do
        delete :destroy_file, on: :collection
        delete :destroy_invoice, on: :collection
      end
      resources :chat_messages, param: :slug, only: [:create]
      
      resources :hc_categories, param: :slug, only: [:index, :show]
      resources :hc_subcategories, param: :slug, only: [:show]
      
      resources :hc_tickets do
        get :divisas, on: :collection
        get :ofertas, on: :collection
        resources :hc_messages, on: :member, only: [:create]
        resources :hc_satisfaction_answers, on: :member, only: [:create]
        post :create_postulacion, on: :member
        get :index_job_applications, on: :collection
        patch :update_postulacion_status, on: :member
        put :assign_assistant, on: :member
      end
    end
    
    root to: "application#index"
  end

  root to: "application#index"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
module Chat
  def self.table_name_prefix
    'chat_'
  end
end

app/models/company.rb
module Company
  def self.table_name_prefix
    "company_"
  end
end

app/models/employee.rb
module Employee
  def self.table_name_prefix
    "employee_"
  end
end

app/models/expense_report.rb
module ExpenseReport
  def self.table_name_prefix
    'expense_report_'
  end
end

app/models/general.rb
module General
  def self.table_name_prefix
    "general_"
  end
end

app/models/helpcenter.rb
module Helpcenter
  def self.table_name_prefix
    'helpcenter_'
  end
end

app/models/library.rb
module Library
  def self.table_name_prefix
    'library_'
  end
end

app/models/location.rb
module Location
  def self.table_name_prefix
    "location_"
  end
end

app/models/marketplace.rb
module Marketplace
  def self.table_name_prefix
    "marketplace_"
  end
end

app/models/media.rb
module Media
  def self.table_name_prefix
    "media_"
  end
end

app/models/menu.rb
module Menu
  def self.table_name_prefix
    'menu_'
  end
end

app/models/news.rb
module News
  def self.table_name_prefix
    "news_"
  end
end

app/models/payment.rb
module Payment
  def self.table_name_prefix
    'payment_'
  end
end

app/models/personal_data.rb
module PersonalData
  def self.table_name_prefix
    'personal_data_'
  end
end

app/models/religion.rb
module Religion
  def self.table_name_prefix
    "religion_"
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :general_users, :join_table => :general_users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/survey.rb
module Survey
  def self.table_name_prefix
    "survey_"
  end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/api_client/_mobile.html.erb
<div class="main clearfix hidden-mobile">
  <div class="column">
    <div id="dl-menu" class="dl-menuwrapper">
      <button class="dl-trigger">Open Menu</button>
      <ul class="dl-menu">
        <li>
          <a href="#">Fashion</a>
          <ul class="dl-submenu">
            <li>
              <a href="#">Men</a>
              <ul class="dl-submenu">
                <li><a href="#">Shirts</a></li>
                <li><a href="#">Jackets</a></li>
                <li><a href="#">Chinos &amp; Trousers</a></li>
                <li><a href="#">Jeans</a></li>
                <li><a href="#">T-Shirts</a></li>
                <li><a href="#">Underwear</a></li>
              </ul>
            </li>
            <li>
              <a href="#">Women</a>
              <ul class="dl-submenu">
                <li><a href="#">Jackets</a></li>
                <li><a href="#">Knits</a></li>
                <li><a href="#">Jeans</a></li>
                <li><a href="#">Dresses</a></li>
                <li><a href="#">Blouses</a></li>
                <li><a href="#">T-Shirts</a></li>
                <li><a href="#">Underwear</a></li>
              </ul>
            </li>
            <li>
              <a href="#">Children</a>
              <ul class="dl-submenu">
                <li><a href="#">Boys</a></li>
                <li><a href="#">Girls</a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /dl-menuwrapper -->
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
  $(function() {
    $( '#dl-menu' ).dlmenu();
  });
</script>

app/views/api_client/menu.html.erb
<html>
<head>
</head>
<body>
<h1>Hola</h1>
</body>
</html>

app/views/layouts/partials/_expense_report_menu.html.erb
<li class="nav-item dropdown <%= dropdown_active?(['expense_report']) %>">
    <a class="nav-link has-dropdown" data-turbolinks="false">
      <i class="fas fa-question-circle"></i><span>Rendición de gastos</span>
    </a>
    <ul class="dropdown-menu">
      <li><%= nav_link "Inbox", inbox_admin_expense_report_requests_path %></li>
      <li><%= nav_link "Rendición de gastos", admin_expense_report_requests_path %></li>
      <% if current_user.is_admin? %>
        <li><%= nav_link "Categorías", admin_expense_report_categories_path %></li>
      <% end %>
    </ul>
  </li>

app/views/layouts/partials/_helpcenter_menu.html.erb
<li class="nav-item dropdown <%= dropdown_active?(['helpcenter']) %>">
  <a class="nav-link has-dropdown" data-turbolinks="false">
    <i class="fas fa-question-circle"></i><span>Proceso de Selección</span>
  </a>
  <ul class="dropdown-menu">
    <!-- <li><%= nav_link "Inbox", inbox_admin_helpcenter_tickets_path %></li> -->
    <li><%= nav_link "Selección", admin_helpcenter_tickets_path %></li>
    <% if current_user.is_admin? %>
      <!-- <li><%= nav_link "Categorías", admin_helpcenter_categories_path %></li>
      <li><%= nav_link "Preguntas", admin_helpcenter_questions_path %></li> -->
    <% end %>

  </ul>
</li>

app/views/layouts/partials/_profiles_menu.html.erb
<li class="nav-item dropdown <%= dropdown_active?(['profiles']) %>">
  <a class="nav-link has-dropdown" data-toggle="dropdown">
    <i class="fas fa-users"></i> <span>Perfilamiento</span>
  </a>
  <ul class="dropdown-menu">
    <li><%= nav_link "Lista de perfiles", admin_profiles_path %></li>
    <li><%= nav_link "Nuevo perfil", new_admin_profile_path %></li>
  </ul>
</li>

app/views/layouts/partials/_surveys_menu.html.erb
<li class="nav-item dropdown <%= dropdown_active?(['surveys', 'answers']) %>">
  <a class="nav-link has-dropdown" data-turbolinks="false"><i class="fas fa-poll-h"></i> <span>Formularios</span></a>
  <ul class="dropdown-menu">
    <li><%= nav_link "Lista de formularios", admin_surveys_path %></li>
    <li><%= nav_link "Lista de respuestas", admin_answers_path %></li>
    <li><%= nav_link "Nuevo formulario", new_admin_survey_path %></li>
  </ul>
</li>

app/views/layouts/partials/_users_menu.html.erb
<li class="nav-item dropdown <%= dropdown_active?(['users']) %>">
  <a class="nav-link has-dropdown" data-turbolinks="false"><i class="fas fa-users"></i> <span>Usuarios</span></a>
  <ul class="dropdown-menu">
    <li><%= nav_link "Lista de usuarios", admin_users_path %></li>
  </ul>
</li>